# Generated by Django 4.2.5 on 2023-09-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_alter_userping_valid_ping_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userping',
            name='valid_ping_count',
            field=models.IntegerField(default=0),
        ),
    ]
