# Generated by Django 4.2.5 on 2023-09-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_alter_deviceping_valid_ping_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceping',
            name='valid_ping_count',
            field=models.IntegerField(default=0),
        ),
    ]
