# Generated by Django 4.2.5 on 2023-09-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private_key',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='public_key',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
